project:
  type: website
  output-dir: docs

website:
  title: "Andrew Ingraham"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Sports Marketing/Analytics"
        href: marketing-analytics.qmd
      - text: "Data Wrangling/Visualization and Rsdtudio"
        href: strategic-marketing.qmd
      - text: "Résumé"
        href: resume.qmd


format:
  html:
    theme: [Slate, theme.scss]
    toc: true

