---
title: "Résumé"
---

```{r knit-resume, echo=FALSE, message=FALSE}
rmarkdown::render(
  "resume/Resume.Rmd",
  output_format = "pdf_document",
  output_file   = "Resume.pdf",
  output_dir    = "resume",
  quiet         = TRUE
)
```


# Professional Summary

By trade I am a laborer and is efficient in the construction field. A background and studying of coding languages and excel files. Skilled in being hands on and being able to learn quickly and think on my feet. Efficient is data wrangling and providing visualization of said data. 

# Technical Skills

- **Programming Languages:** R, Python, Excel  
- **Web Technologies:** HTML, Quarto, Excel, Analytics Tools

# Education

| Degree                             | Year                          | College / Department                 | Institution         |
| ---------------------------------- | ----------------------------- | ------------------------------------ | ------------------- |
| [Studying to Get my Undergrad]                     | [Start – 2022]     | [College of Business]        | [Cal Poly Pomona]   |


# Work Experience

### [Laborer, [Ley Drew INC]  
*[2018-Now]*

- [Cleaning up the worksite]  
- [Helping with Framing]  
- [Doing what I am Told to Do]  
- [Efficient in Power Tools]  

---

### [Salesmen], [Starberry Farms]  
*[2019-2021]*

- [Selling Christmas Trees]  
- [Bringing Christmas Trees to Cars]  
- [Attaching Trees to Cars]  
- [Being Efficient in Communcating with Customers]  

---