---
title: "Data Wrangling/Visualization and Rsdtudio"
---

Below is a project/assigment I did for my CIS3100 class. This illustrates my skills in data wrangling and in visualization. Through this you can see what codes I used to wrangle said data. You can also see my graphs and charts that I have also created to correlate with the data that i have wrangled.



## [Project Title: M05-Application-Data_Wrangling_Tidyverse]

For my class I had too answer many challenging questions. This included the questions about wrangling certain data from datasets. I also had to create charts and graphs to visual the data that i have wrangled. You can also see in majority of the questions I have added different kinds of graphs and charts. You can see that I have made numbers or words on the y and x axis and I made it so they have multiple color indicators as well as otehr useful things.

**Skills Demonstrated:**

- **Data Wrangling:** Took data from datasets and layed out the data that was needed.
- **Visualization:** Turned that data into visual charts and graphs. 
- **Customization:** I made color indicators and added legends to the graphs and charts.
- **Use of Ggplot2:** Used the package ggplot to develop my graphs and charts.

Below is an embedded demonstration of the interactive report:


<iframe src="data/Data-Wrangling.html" width="100%" height="600px" style="border: none;"></iframe>

---
